# Generated by Django 3.0.2 on 2020-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=30, unique=True)),
                ('dateTime', models.DateTimeField()),
                ('pH', models.FloatField()),
                ('DO', models.FloatField()),
                ('NH4', models.FloatField()),
                ('CODMn', models.FloatField()),
                ('TOC', models.CharField(max_length=10)),
                ('level', models.CharField(max_length=10)),
                ('attribute', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '站点',
                'unique_together': {('id', 'siteName')},
            },
        ),
    ]
