# Generated by Django 3.0.2 on 2020-02-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0002_auto_20200213_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenode',
            name='CODMn',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sitenode',
            name='DO',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sitenode',
            name='NH4',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sitenode',
            name='pH',
            field=models.CharField(max_length=10),
        ),
    ]
