# Generated by Django 3.0.2 on 2020-02-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0003_auto_20200213_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitenode',
            name='attribute',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
