# Generated by Django 3.0.2 on 2020-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0004_auto_20200213_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitenode',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
