# Generated by Django 3.0.2 on 2020-02-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0005_sitenode_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitenode',
            name='add_time',
        ),
    ]
