# Generated by Django 3.0.2 on 2020-02-14 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0006_remove_sitenode_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitenode',
            options={'ordering': ['id'], 'verbose_name': '站点'},
        ),
    ]
