# Generated by Django 3.0.2 on 2020-02-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0007_auto_20200214_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitenode',
            options={'ordering': ['-id'], 'verbose_name': '站点'},
        ),
    ]
