# Generated by Django 3.0.2 on 2020-03-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitenode', '0008_auto_20200214_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitenode',
            unique_together={('siteName', 'dateTime')},
        ),
        migrations.AlterModelTable(
            name='sitenode',
            table='site_node',
        ),
    ]
