# Generated by Django 3.0.2 on 2020-01-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logup_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
