# Generated by Django 3.0.2 on 2020-02-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200125_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='img/default.png', upload_to='img'),
        ),
    ]
