# Generated by Django 3.0.2 on 2020-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_avator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avator',
            new_name='avatar',
        ),
    ]
